data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data$Time <- paste(data$Date, ":", data$Time)
data$Time <- strptime(data$Time, "%d/%m/%Y : %H:%M:%S")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
startDate <- as.Date("2007-02-01", "%Y-%m-%d")
endDate <- as.Date("2007-02-02", "%Y-%m-%d")
useData <- subset(data, Date>=startDate & Date<=endDate)
useData2 <- subset(useData, weekdays(Date)=="Thursday" | weekdays(Date)=="Friday" | weekdays(Date)=="Saturday")
png(file="plot2.png")
plot(useData2$Time, useData2$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.off()