data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data$Time <- paste(data$Date, ":", data$Time)
data$Time <- strptime(data$Time, "%d/%m/%Y : %H:%M:%S")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
startDate <- as.Date("2007-02-01", "%Y-%m-%d")
endDate <- as.Date("2007-02-02", "%Y-%m-%d")
useData <- subset(data, Date>=startDate & Date<=endDate)
useData2 <- subset(useData, weekdays(Date)=="Thursday" | weekdays(Date)=="Friday" | weekdays(Date)=="Saturday")
png(file="plot3.png")
with(useData2, plot(Time, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering"))
with(useData2, lines(Time, Sub_metering_1))
with(useData2, lines(Time, Sub_metering_2, col="red"))
with(useData2, lines(Time, Sub_metering_3, col="blue"))
legend("topright", lty="solid", col=c("black", "red", "blue"), legend=c("Sub metering 1", "Sub metering 2", "Sub metering 3"))
dev.off()