data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data$Time <- paste(data$Date, ":", data$Time)
data$Time <- strptime(data$Time, "%d/%m/%Y : %H:%M:%S")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
startDate <- as.Date("2007-02-01", "%Y-%m-%d")
endDate <- as.Date("2007-02-02", "%Y-%m-%d")
useData <- subset(data, Date>=startDate & Date<=endDate)
png(file="plot1.png")
hist(useData$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()